igorbarinov/awesome-bitcoin

README.md

Add book Mastering Bitcoin

---

README.md

Add open source wallets

---

README.md

Add toshi server

---

README.md

quick fix. 
Thanks for the awesome!

fixed typo: Genle -> Gentle

---

README.md

Also has a Github repo, if needed:
https://github.com/spesmilo/electrum

Add Electrum bitcoin client

---

README.md

Added Smartbit for API, WebServices and Explorer

update readme to include Smartbit

---

README.md

Not sure about category, because it's not library.

Add awesome-cryptocoinjs

---

README.md

I added the XChange library for Java.

Added XChange

---

README.md

Feel free to edit what I wrote. It's your branch, after all.

Add pycoin to README.

---

README.md

From the bitkit site:
> Bitkit is a tool that makes waiting for your Bitcoin transaction to confirm a little more interesting. It shows in real time the relative position of your transaction in the Bitcoin mempool according to the fee rate, accounting for any ancestor or descendant transactions.

Add Bitkit to Blockchain Explorers

---

README.md

fix c++ link

---

README.md

Add Bitcoin-S to list of libraries

---

README.md

I added "Bitcoin Learning Master List" but thought after that it isn't really a developers resource.. so found more appropriate links to add to "Additional Resources" category.

correct mistakenly placed link

---

README.md

oogway is a Bitcoin utility library for Python with a focus on security and simplicity.
Docs available at [oogway.6conf.com](https://oogway.6conf.com)

add oogway: A Bitcoin utility library for Python

---

README.md

Hey @igorbarinov 
just removing a dead link.
Cheers!

Removing dead link https://webbtc.com/script

---

README.md

https://github.com/paulmillr/scure-btc-signer

Add scure-btc-signer.

---

README.md

https://github.com/GigaBitcoin/secp256k1.swift - [Documentation](https://swiftpackageindex.com/GigaBitcoin/secp256k1.swift/0.10.0/documentation/secp256k1)

Add secp256k1.swift

---

README.md

Update libsecp256k1 details

---

README.md

Cryptocurrency Alerting is pretty useful for bitcoin wallet alerts. Thanks!

Add cryptocurrency alerting

---

README.md

I have added a new blockchain data provider (Bitquery). **Bitquery** is a leading provider of blockchain data analytics, offering a suite of products that enables cross-chain analytics, DEX trading insights, and DeFi protocols APIs.

Added new blockchain data provider API (Bitquery)

---

README.md

Works since 2015. https://github.com/CoinSpace/CoinSpace.

Add Coin Wallet

---

README.md

Add sparrow wallet

---

README.md

Added Satonomics via a PR as requested in #115

Add Satonomics to "Blockchain API and Web services"

---

README.md

`bitcoin-sdk-js` is well tested and documented javascript library, which helps to create various type of bitcoin transaction so easily.

feat: add bitcoin-sdk-js

---

README.md

Joinmarket coinjoin implementation and it's user friendly frontend Jam

Add privacy projects

---

README.md

This PR updates the description of Maestro so that it is better positioned for SEO

update readme with SEO-optimized description for Maestro

---

README.md

Adding BTC Tooling - a Bitcoin dashboard with real-time data visualization and market tools to the utilities section.

Add BTC Tooling to utilities section
